name: Amazon Deal Monitor with Secrets

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Py
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set figs
        run: |
          cat > config.json <<EOL
          {
            "priority_category": ["Electronics"],
            "regular_category": ["Office Products", "Sports and Outdoors", "Toys and Games", "Video Games", "Automotive", "Cell Phones and Accessories", "Appliances"],
            "price_off": [60, 70, 80, 90, 99],
            "other_webhook": "${{ secrets.OTHER_WEBHOOK }}",
            "filters": [
              {
                "criteria": {
                  "average_price_min": 1,
                  "average_price_max": 150,
                  "percent_off_min": 60,
                  "percent_off_max": 99,
                  "categories": ["category1", "all"]
                },
                "webhooks": [
                  {
                    "webhook": ["${{ secrets.MAIN_WEBHOOK }}"],
                    "role": "${{ secrets.ROLE_ID }}"
                  }
                ],
                "isolated": true
              }
            ],
            "embed_data": {
              "username": "${{ secrets.BOT_USERNAME }}",
              "avatar_url": "${{ secrets.EMBED_URL }}",
              "author_name": "Amazon Deals",
              "author_icon_url": "${{ secrets.EMBED_URL }}",
              "footer": "Happy Shopping!",
              "footer_icon": "${{ secrets.EMBED_URL }}",
              "color": 16711680
            }
          }
          EOL

      - name: Install dep
        run: pip install -r requirements.txt

      - name: Run
        run: python main.py
